### ISSUE TITLE
Required fields are not checked

### ISSUE THREAD

**Issue by FlipZoomMedia** [MadeMyDay/PageTableExtended#14]
I have defined in a template all fields as "required", but if I in the modal window and click "publish", the modal window will be closed. It is not checked whether required fields have been filled.

**Comment by MadeMyDay** [comment]
Have you checked if the same occurs in PageTable? I haven’t altered the behavior of the modals, so I think you should file a bug in Ryan’s repo.

**Comment by FlipZoomMedia** [comment]
You're right. Thanks for the info.
