### ISSUE TITLE
conflicts with pageTable in same template

### ISSUE THREAD

**Issue by iamwebrocker** [MadeMyDay/PageTableExtended#19]
if both original "_pageTable_" and "_pageTableExtended_" fields are used in the same template, funny things happen.
(note: I'm not sure if this is a valid usecase at all, since why use both fieldtypes?)
That aside, if you happen to use both fields together here's what happened in my case:
in the "normal" pageTable field the add action was fired twice - right after saving a newly created element, a second one would immediatly be created. Using the trash icon in the pageTable row resulted in nothing - the row is not deletable.
In the pageTableExtended field's admin view the trash is also not working.
Without knowing the internal workings, is it possible that the pageTableExtended does not extend, but duplicate the pageTable's settings, including the same JS et al?
If the pageTableExtended is meat to replace and enhance the pageTable, maybe a check if the original pageTable is installed and alerting some hint would be helpful to clumsy users like me :-)
cheers,
Tom

**Comment by tbba** [comment]
Hi Tom, just by change: Is the "autojoin" option set "on" for any of the conflicting fields? 
If so, can you switch that off?
related:
https://processwire.com/talk/topic/10496-autojoin-in-complex-setups-page-field-with-multiple-pages/

**Comment by iamwebrocker** [comment]
hi Carl,
the pageTable and the pageTableExtended fields are not set to autojoin. But the template of the pages that are "addressed" by the pageTable/Extended field have the "title" field, which is set to autojoin by default, I think.

**Comment by deeplypixelating** [comment]
I ran across this bug as well.  Are lines 26 and 28 in `InputfieldPageTableExtended.module` pointing to the correct files?  I assume this is trying to load the module's files (`InputfieldPageTableExtended.js` and `.css`), but they're pointing to the core module's files.  Maybe it's doubling up on the event hooks?

```
$this->config->scripts->add($this->config->urls->InputfieldPageTable . "InputfieldPageTable.js");
$this->config->styles->add($this->config->urls->InputfieldPageTable . "InputfieldPageTable.css");
```

**Comment by ottogal** [comment]
I confirm the issue (Add action firing twice, trash not working).
A soon fix would be much appreciated.

**Comment by deeplypixelating** [comment]
Submitted a pull request here, should fix the issue: https://github.com/MadeMyDay/PageTableExtended/pull/21

**Comment by MadeMyDay** [comment]
will look into it

**Comment by MadeMyDay** [comment]
I just ran into this issue but with the your fix added @deeplypixelating : JS and CSS are not loaded if just a single PTE is running on the page. So it seems the if condition doesn't work?

**Comment by somatonic** [comment]
I couldn't reproduce this issue mentioned by the OP. It works well with PageTable and PageTableExtended field on same template.

**Comment by iamwebrocker** [comment]
since @MadeMyDay did a major update and I currently have no PTE in use, I'm closing this. 
Please re-open if you run into this issue
